--TABLE "users"
BEGIN;

CREATE TABLE "users" (
    "Id" SERIAL NOT NULL,
    "FirstName" VARCHAR(75) NOT NULL,
    "LastName" VARCHAR(75) NOT NULL,
    "Email" VARCHAR(100) NOT NULL,
    "Password" VARCHAR(100) NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
    CONSTRAINT "USERS_PK_Id" PRIMARY KEY ("Id")
) TABLESPACE pg_default;

COMMIT;